name: Telegram Notify on Commit

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Send Telegram Message to Channel
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
      run: |
        MESSAGE_ID=$(curl -s -X POST https://api.telegram.org/bot7116891407:AAF3efNnaFo1gF8zn5PkJIAWci4bkt_hoOw/sendMessage \
          -d chat_id="-1002265196291" \
          -d text="📢 Tool *$GITHUB_REPOSITORY* có update: [$GITHUB_COMMIT_MESSAGE](https://github.com/$GITHUB_REPOSITORY?tab=readme-ov-file#$GITHUB_COMMIT_MESSAGE) " \
          -d parse_mode="Markdown" | jq -r '.result.message_id')
        
        curl -s -X POST https://api.telegram.org/bot7116891407:AAF3efNnaFo1gF8zn5PkJIAWci4bkt_hoOw/forwardMessage \
          -d chat_id="-1002021638546" \
          -d from_chat_id="-1002265196291" \
          -d message_id=$MESSAGE_ID